{% set name = "motionless" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/motionless-{{ version }}.tar.gz
  sha256: cc1785599659fbec7358ed9f5af5460cfcc189e7e7e6116c0332888e059c9a60

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - motionless
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ryancox/motionless
  summary: 'motionless is a Python library that takes the pain out of generating Google Static Map URLs'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TimoRoth
